version: '3.8'

services:
  db:
    image: postgres:13
    container_name: nextjs_graphql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
